In [37]:
import numpy as np
A = np.array([1, 2, 3, 4])
a = A.tolist()
print(a)

V = np.array([[4, 6, 9], [12, 10, 7], [50, 25, 11]])
print(V)
S = np.trace(V)
print(S)

a = np.array([[1, 2], [3, 5]])
X = 2
b = a[a>X]
for i in b:
    print(i, "Est supérieur à 2")


array_1 = ([[7, 4, 5], [3, 8, 2]])
array_2 = ([[5, 1, 3], [6, 2, 9]])
C = np.add(array_1,array_2)
print(C)

import statistics
K = np.array([[7, 4, 5], [3, 6, 8], [2, 9, 15]])
W_A = np.mean(K)

print(W_A)





[1, 2, 3, 4]
[[ 4  6  9]
 [12 10  7]
 [50 25 11]]
25
3 Est supérieur à 2
5 Est supérieur à 2
[[12  5  8]
 [ 9 10 11]]
6.555555555555555
